name: test
permissions:
  contents: write
on:
  watch:
    types: started
  workflow_dispatch:
  # schedule:
  #   - cron: '00 00 * * *'
  fork:
    types: [created]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies ðŸ“¦
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }} ðŸš€
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm ðŸš€
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install dependencies ðŸš€
        run: pnpm install

      - name: test ðŸš€
        run: pnpm run test

      - name: Create and write to info.log ðŸš€
        run: |
          echo "Triggered by schedule at $(date)" > docs/log.txt

      - name: Commit files  ðŸš€
        run: |
          git add docs/log.txt
          git config --local user.email "action@h7ml.cn"
          git config --local user.name "github-actions[bot]"
          git commit --allow-empty -m ":rocket: Update today's hot rank on $(date)" -a
      - name: Push changes  ðŸš€
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: update cache ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: master
          folder: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
